### ISSUE TITLE
The project in this repository involves fake open source！！！

### ISSUE THREAD

**Issue by zhanghao328** [fkie/fkie-nbv-planner#6]
**A warning to all users intending to reproduce or compare results using this code package: the open-source package provided by the author cannot be reproduced and contains numerous bugs. The instructions for running the code are also vague and incomplete. I plan to report these issues in the hope of reducing such deceptive practices.**

**Comment by mnksnz** [comment]
Thank you for taking the time to share your concerns with the fellow users. I will consider to look into the issue and assist you further if you provide a concrete description of the problem preferably in a respectable manner.

I will close this issue due to the lack of detailed information to assist you further.
